language: ruby
bundler_args: --without guard
rvm:
  - "2.0"
  - "2.1"
  - ruby-head
script: "bundle exec rspec"
addons:
  code_climate:
    repo_token: ''
branches:
  only: master
notifications:
  email: false